---
build: false
platform: x86

clone_folder: c:\tesseract-ocr-for-php

install:
  - choco install php
  - choco install capture2text
  - choco install composer
  - refreshenv
  - cd c:\tesseract-ocr-for-php
  - composer install

test_script:
  - vendor\bin\phpunit -c phpunit.xml

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/b48c69af70a9047dba30
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
