---
os: linux
sudo: required

language: php
php: 7.2

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - env: TESSERACT_VERSION=3.03.02-3
    - env: TESSERACT_VERSION=3.03.03-1
    - env: TESSERACT_VERSION=3.04.01-4
    - env: TESSERACT_VERSION=3.04.01-5
#    - env: TESSERACT_VERSION=3.04.01-6 weird build error because of docker, will check later

services:
  - docker

before_script:
  - composer install

script:
  - vendor/bin/phpunit -c phpunit.xml $(test -v TESSERACT_VERSION || echo tests/UnitTests.php)

after_success:
  - test -v TESSERACT_VERSION && vendor/bin/codacycoverage clover ./coverage.xml

notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/acba3130175a3a47266d'
    on_success: always
    on_failure: always
    on_start: always
